version: '3'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/rstudio/iq-manual
    environment:
      - PASSWORD=openthegate      
      - DISABLE_AUTH=true
    ports:
      - 8787:8787
